Controllers/AntrenorAnaPanelController.cs
using DataAccessLayer.Concrete;
using FitnessApp1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.Runtime.InteropServices;

namespace FitnessApp1.Controllers
{
    public class AntrenorAnaPanelController : Controller
    {
        private readonly Context _context;

        public AntrenorAnaPanelController(Context context)
        {
            _context = context;
        }

        public IActionResult Index(int antrenorId)
        {
            ViewBag.Id = antrenorId;
            // İlgili antrenör ID'sine sahip kullanıcıları getir
            List<kullanici> kullaniciListesi = _context.Kullanicilar.Where(k => k.antrenor_id == antrenorId).ToList();
            List<antrenor1> antrenorListesi = _context.Antrenorler.Where(k => k.antrenor_id == antrenorId).ToList();
            String picture = "";

            foreach (var item in antrenorListesi)
            {
                picture = item.picture;
            }
            ViewBag.picture = picture;

            // Model oluştur ve kullanıcıları bu modele ata
            var model = new AntrenorKullaniciViewModel
            {
                KullaniciListesi = kullaniciListesi
            };

            // View'e modeli gönder
            return View(model);
        }
        public IActionResult Index3(int antrenor_id, int kullanici_id)
        {
            List<kullanici> kullaniciListesi = _context.Kullanicilar.Where(k => k.kullanici_id == kullanici_id).ToList();
            List<antrenor1> antrenorListesi = _context.Antrenorler.Where(k => k.antrenor_id == antrenor_id).ToList();
            String pictureAntrenor = "";

            foreach (var item in antrenorListesi)
            {
                pictureAntrenor = item.picture;
            }
            ViewBag.pictureAntrenor = pictureAntrenor;
            String pictureKullanici = "";

            foreach (var item in kullaniciListesi)
            {
                pictureKullanici = item.picture;
            }
            ViewBag.pictureKullanici = pictureKullanici;
            ViewBag.antrenor_id = antrenor_id;
            ViewBag.kullanici_id = kullanici_id;


            List<mesaj> mesajlarim = _context.Mesajlarım
        .Where(m => (m.gonderen_id == antrenor_id && m.durum_kontrol == true && m.alici_id == kullanici_id) || (m.alici_id == antrenor_id && m.durum_kontrol == false && m.gonderen_id == kullanici_id))
        .ToList();
            var model = new MesajViewModel
            {
                Mesajlar = mesajlarim
            };





            return View(model);
        }


        public IActionResult Index1(int kullanici_id, int antrenor_id)
        {
            ViewBag.id = kullanici_id;
            ViewBag.antrenor_id = antrenor_id;
            List<beslenme_programi> beslenmeprogrami = _context.BeslenmeProgramlari
                .Where(k => k.antrenor_id == antrenor_id && k.kullanici_id == kullanici_id)
                .ToList();
            List<egzersiz_programi> egzersizprogrami = _context.EgzersizProgramlari
     .Where(k => k.antrenor_id == antrenor_id && k.kullanici_id == kullanici_id)
     .ToList();

            List<guncel_versiyon> guncelverisyon = _context.GuncelVersiyon
                .Where(k => k.kullanici_id == kullanici_id)
                .ToList();

            var model = new AntrenorKullaniciAnaTablolar
            {
                EgzersizProgramlari = egzersizprogrami,
                BeslenmeProgramlari = beslenmeprogrami,
                GuncelVersiyonlari = guncelverisyon
            };




            return View(model);
        }
        public IActionResult Index2(int antrenor_id)
        {

            List<antrenor1> antrenor = _context.Antrenorler.Where(k => k.antrenor_id == antrenor_id).ToList();

            var model = new AntrenorViewModel
            {
                Antrenorler = antrenor

            };




            return View(model);
        }

        public IActionResult EgzersizDelete(int kullanici_id, int antrenor_id, int id)
        {
            string deleteQuery = "DELETE FROM egzersiz_programi WHERE id =@id ";

            _context.Database.ExecuteSqlRaw(deleteQuery,

                new SqlParameter("@id", id));

            return RedirectToAction("Index1", new { kullanici_id = kullanici_id, antrenor_id = antrenor_id });
        }

        public List<mesaj> TumMesajlariGetir()
        {
            List<mesaj> mesaj = _context.Mesajlarım.ToList();
            return mesaj;
        }

        [HttpPost]
        public IActionResult AntrenorMesajGonder(int kullanici_id, int antrenor_id, string mesaj)
        {

            try
            {
                string sql = "INSERT INTO mesaj (gonderen_id, alici_id, text, durum_kontrol) VALUES ({0}, {1}, {2}, {3})";
                _context.Database.ExecuteSqlRaw(sql, antrenor_id, kullanici_id, mesaj, true);

                return RedirectToAction("Index3", new { antrenor_id = antrenor_id, kullanici_id = kullanici_id });
            }
            catch (Exception ex)
            {
                ViewBag.UpdateError = "Bir hata oluştu. Lütfen tekrar deneyin.";
                return RedirectToAction("Index3", new { antrenor_id = antrenor_id, kullanici_id = kullanici_id });
            }
        }

        public IActionResult BeslenmeDelete(int kullanici_id, int antrenor_id, int id)
        {
            string deleteQuery = "DELETE FROM beslenme_programi WHERE id =@id ";

            _context.Database.ExecuteSqlRaw(deleteQuery,

                new SqlParameter("@id", id));

            return RedirectToAction("Index1", new { kullanici_id = kullanici_id, antrenor_id = antrenor_id });
        }

        public List<beslenme_programi> TumBeslenmeleriGetir()
        {
            List<beslenme_programi> beslenmeler = _context.BeslenmeProgramlari.ToList();
            return beslenmeler;
        }
        [HttpPost]
        public IActionResult BeslenmeEkle(int kullanici_id, int antrenor_id, int hedef, int kalori_hedef, string gunluk_ogun)
        {
            try
            {

                List<beslenme_programi> beslenmelerler = TumBeslenmeleriGetir();
                int idm = 0;
                foreach (var item in beslenmelerler)
                {
                    idm = item.id;

                }
                idm += idm;
                // Yeni veriyi oluştur
                var yenibeslenme = new beslenme_programi
                {
                    id = idm,
                    kullanici_id = kullanici_id,
                    antrenor_id = antrenor_id,
                    hedef = hedef,
                    kalori_hedef = kalori_hedef,
                    gunluk_ogun = gunluk_ogun
                };

                // Veritabanına yeni veriyi ekle
                _context.BeslenmeProgramlari.Add(yenibeslenme);
                _context.SaveChanges();

                return RedirectToAction("Index1", new { kullanici_id = kullanici_id, antrenor_id = antrenor_id }); // Ekleme başarılıysa Index sayfasına yönlendir
            }
            catch (Exception ex)
            {
                // Hata durumunda hata mesajıyla birlikte Index sayfasına geri dön
                ViewBag.UpdateError = "Bir hata oluştu. Lütfen tekrar deneyin.";
                return RedirectToAction("Index", new { id = kullanici_id });
            }
        }


        [HttpPost]
        public IActionResult Guncelle(string ad, string soyad, string eposta, string telefon, int uzmanlik, int a_id, string picture)
        {
            try
            {
                var antrenor = _context.Antrenorler.FirstOrDefault(a => a.antrenor_id == a_id);
                if (antrenor != null)
                {
                    antrenor.antrenor_ad = ad;
                    antrenor.antrenor_soyad = soyad;
                    antrenor.e_posta = eposta;
                    antrenor.telefon = telefon;
                    antrenor.uzmanlik = uzmanlik;
                    antrenor.picture = picture;

                    _context.SaveChanges();
                }

                return RedirectToAction("Index", new { antrenorId = a_id });
            }
            catch (Exception ex)
            {
                ViewBag.UpdateError = "Güncelleme işlemi sırasında bir hata oluştu. Lütfen tekrar deneyin.";
                return RedirectToAction("Index");
            }
        }
        public List<egzersiz_programi> TumEgzersizleriGetir()
        {
            List<egzersiz_programi> egzersizler = _context.EgzersizProgramlari.ToList();
            return egzersizler;
        }
        [HttpPost]
        public IActionResult EgzersizEkle(int kullanici_id, int antrenor_id, int hedef, int set_sayi, string video_link, DateTime baslama_tarih, string program_sure, string egzersiz_ad)
        {
            try
            {

                List<egzersiz_programi> egzersizler = TumEgzersizleriGetir();
                int idm = 0;
                foreach (var item in egzersizler)
                {
                    idm = item.id;

                }
                idm += idm;
                // Yeni veriyi oluştur
                var yeniEgzersiz = new egzersiz_programi
                {
                    id = idm,
                    kullanici_id = kullanici_id,
                    antrenor_id = antrenor_id,
                    hedef = hedef,
                    set_sayi = set_sayi,
                    video_link = video_link,
                    baslama_tarih = baslama_tarih,
                    program_sure = program_sure,
                    egzersiz_ad = egzersiz_ad
                };

                // Veritabanına yeni veriyi ekle
                _context.EgzersizProgramlari.Add(yeniEgzersiz);
                _context.SaveChanges();

                return RedirectToAction("Index1", new { kullanici_id = kullanici_id, antrenor_id = antrenor_id }); // Ekleme başarılıysa Index sayfasına yönlendir
            }

Views/AntrenorAnaPanel/Index.cshtml
@using FitnessApp1.Models
@model AntrenorKullaniciViewModel
<style>
    .sidebar {
        width: 170px; /* Yan menünün genişliği */
        background-color: yellowgreen; /* Yan menü arka plan rengi */
        height: 100%; /* Sayfa boyunca uzunluk */
        position: fixed; /* Sabit konum */
        top: 0; /* Üstten başlama pozisyonu */
        left: 0; /* Soldan başlama pozisyonu */
        overflow-x: hidden; /* Yatay scrollbar'ı gizle */
        padding-top: 20px;
    }

        .sidebar a {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 20px;
            color: #000;
            display: block;
        }

            .sidebar a:hover {
                background-color: #ddd; /* Fare üstüne gelindiğinde arka plan rengi */
            }


    h1 {
        color: rosybrown; /* Başlık rengi */
        font-family: 'Times New Roman', Times, serif, sans-serif; /* Başlık fontu */
        margin-top: 200px;
        margin-left: 40px;
    }

    .button-background {
        margin-top: 70px;
        width: 350px;
        height: 500px;
        background-image: url('https://i.pinimg.com/474x/28/e7/ce/28e7cee8096f263938261641038f1fd1.jpg');
        background-size: cover;
        background-position: top;
        /* Yuvarlak bir arka plan oluşturmak için */
        flex-shrink: 0; /* Boyutun küçülmemesini sağla */
    }

    label {
        display: block;
        margin-bottom: 5px;
        color: rosybrown;
    }

    h2 {
        color: yellowgreen; /* Başlık rengi */
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        margin-left: 100px;
        margin-top: 50px;
        font-size: 30px;
    }

    input[type="submit"] {
        width: 200px; /* Genişlik */
        height: 40px; /* Yükseklik */
        background-color: wheat; /* Arka plan rengi */
        color: rosybrown; /* Yazı rengi */
        border: none; /* Kenarlık olmadan */
        border-radius: 5px; /* Kenar yuvarlama */
        cursor: pointer; /* Fare üzerine gelince işaretçi tipi */
        margin-top: 10px; /* Butonlar arası boşluk */
        font-size: 16px; /* Yazı boyutu */
    }


        /* İlgili butonun üzerine gelindiğinde stilini değiştirme */
        input[type="submit"]:hover {
            background-color: yellow; /* Hover rengi */
        }

    button {
        color: yellowgreen;
        background-color: black;
    }

    table {
        margin-left: 85px;
        border-collapse: collapse;
        width: 100%;
        background-color: white;
    }

    th, td {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        color: black;
    }

    th {
        background-color: yellowgreen;
    }

    tr:nth-child(even) {
        background-color: lightyellow;
    }

    body {
        background-image: url('https://i.pinimg.com/564x/cf/8b/8b/cf8b8bd73856fc7df8374a5a650c7bb5.jpg'); /* Arkaplan resminin URL'sini buraya ekleyin */
        background-size: center; /* Resmi ekran boyutuna uyacak şekilde ölçeklendir */
        background-position: right; /* Resmi ortala */
    }
</style>

<h2>Öğrencileriniz</h2>
<div class="sidebar">
    @if (ViewBag.picture == "")
    {
        <img src="https://i.pinimg.com/474x/fd/81/76/fd81760500afdbae097cb23b1b720c76.jpg" width="150" height="150">
    }
    @if (ViewBag.picture != "")
    {
        <img src="@ViewBag.picture" width="150" height="150">
    }

    <form method="post" asp-controller="AntrenorAnaPanel" asp-action="Index2">
        <input type="hidden" name="antrenor_id" value="@ViewBag.Id" />
        <button type="submit">&#128100;Profilim</button>
    </form>

</div>
<table>
    <thead>
        <tr>
            <th>Ad</th>
            <th>Soyad</th>
            <th>Doğum Tarihi</th>
            <th>Cinsiyet</th>
            <th>Eposta</th>
            <th>Telefon</th>

            <th>Hedef</th>
            <th>Düzenle</th>
            <!-- Diğer sütunlar -->
        </tr>
    </thead>
    <tbody>
        @foreach (var kullanici in Model.KullaniciListesi)
        {


            <tr>
                <td>@kullanici.kullanici_ad</td>
                <td>@kullanici.kullanici_soyad</td>
                <td>@kullanici.dogum_tarih.ToShortDateString()</td>
                <td>@kullanici.cinsiyet</td>
                <td>@kullanici.e_posta</td>
                <td>@kullanici.telefon</td>

                <td>
                    @if (kullanici.hedef == 1)
                    {
                        <text>Kilo kazanma</text>
                    }
                    else if (kullanici.hedef == 2)
                    {
                        <text>Kilo kaybetme</text>
                    }
                    else if (kullanici.hedef == 3)
                    {
                        <text>Kilo koruma</text>
                    }
                    else if (kullanici.hedef == 4)
                    {
                        <text>Kas kazanma</text>
                    }
                </td>
                <!-- ... Diğer sütunlar ... -->
                <td>
                    <form method="post" asp-controller="AntrenorAnaPanel" asp-action="Index1">
                        <input type="hidden" name="kullanici_id" value="@kullanici.kullanici_id" />
                        <input type="hidden" name="antrenor_id" value="@ViewBag.Id" />
                        <button type="submit">Bilgiler</button>
                    </form>
                </td>
            </tr>



        }
    </tbody>
</table>

Views/AntrenorAnaPanel/Index2.cshtml
@model FitnessApp1.Models.AntrenorViewModel
<style>

    .sidebar {
        width: 700px; /* Yan menünün genişliği */
        background-color: yellowgreen; /* Yan menü arka plan rengi */
        height: 100%; /* Sayfa boyunca uzunluk */
        position: fixed; /* Sabit konum */
        top: 0; /* Üstten başlama pozisyonu */
        left: 0; /* Soldan başlama pozisyonu */
        overflow-x: hidden; /* Yatay scrollbar'ı gizle */
        padding-top: 20px;
        flex-direction: column;
        display: block;
        text-align: center;
    }

        .sidebar label {
            color: black;
        }

        .sidebar p {
            background-color: white; /* Beyaz arka plan */
            padding: 2px; /* İstediğiniz boşluğu verebilirsiniz */
        }

        .sidebar a {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 20px;
            color: #000;
            display: block;
        }

            .sidebar a:hover {
                background-color: yellow;
            }


    h1 {
        color: rosybrown; /* Başlık rengi */
        font-family: 'Times New Roman', Times, serif, sans-serif;
        margin-top: 200px;
        margin-left: 40px;
    }

    .button-background {
        margin-top: 70px;
        width: 350px;
        height: 500px;
        background-image: url('https://i.pinimg.com/564x/2b/e6/31/2be631e3afc5ba303f6315ba8d4c41f3.jpg');
        background-size: cover;
        background-position: top;
        /* Yuvarlak bir arka plan oluşturmak için */
        flex-shrink: 0; /* Boyutun küçülmemesini sağla */
    }

    label {
        display: block;
        margin-bottom: 5px;
        color: rosybrown;
    }

    h2 {
        color: yellowgreen; /* Başlık rengi */
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        margin-left: 100px;
        margin-top: 50px;
        font-size: 30px;
    }

    input[type="submit"] {
        width: 200px; /* Genişlik */
        height: 40px; /* Yükseklik */
        background-color: yellowgreen; /* Arka plan rengi */
        color: black; /* Yazı rengi */
        border: none; /* Kenarlık olmadan */
        border-radius: 5px; /* Kenar yuvarlama */
        cursor: pointer; /* Fare üzerine gelince işaretçi tipi */
        margin-top: 10px; /* Butonlar arası boşluk */
        font-size: 16px; /* Yazı boyutu */
    }


        /* İlgili butonun üzerine gelindiğinde stilini değiştirme */
        input[type="submit"]:hover {
            background-color: yellow; /* Hover rengi */
        }

    button {
        color: yellowgreen;
        background-color: black;
    }

    table {
        margin-top: 120px;
        margin-left: 720px;
        color: yellowgreen;
    }

    th, td {
        padding-top: 100px;
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        color: black;
    }

    th {
        background-color: yellowgreen;
    }

    tr:nth-child(even) {
        background-color: lightyellow;
    }

    body {
        background-image: url('https://i.pinimg.com/564x/cf/8b/8b/cf8b8bd73856fc7df8374a5a650c7bb5.jpg'); /* Arkaplan resminin URL'sini buraya ekleyin */
        background-size: center; /* Resmi ekran boyutuna uyacak şekilde ölçeklendir */
        background-position: right; /* Resmi ortala */
    }
</style>
<div class="sidebar">

    
    @foreach (var antrenor in Model.Antrenorler)
    {
        <div style="margin-top:120px">

           <img src="@antrenor.picture" width="120" height="120">

            <p><label>Antrenor Adı:</label> @antrenor.antrenor_ad</p>
            <p><label>Antrenor Soyadı:</label> @antrenor.antrenor_soyad</p>
            <p><label>Antrenor E-posta  &#128231;:</label> @antrenor.e_posta</p>
            <p><label>Antrenor Telefon &#9742;:</label> @antrenor.telefon</p>
            <p><label>Antrenör ID:</label> @antrenor.antrenor_id</p>
            <p><label>Uzmanlık:</label> @antrenor.uzmanlik</p>

        </div>

    }

</div>
<table>
    @foreach (var antrenor in Model.Antrenorler)
    {
        <tr>

            <td>
                <form asp-controller="AntrenorAnaPanel" asp-action="Guncelle" method="post">
                    <input type="hidden" name="a_id" value="@antrenor.antrenor_id" />
                    <label for="ad">Ad:</label>
                    <input type="text" id="ad" name="ad" value="@antrenor.antrenor_ad" /><br />
                    <label for="soyad">Soyad:</label>
                    <input type="text" id="soyad" name="soyad" value="@antrenor.antrenor_soyad" /><br />
                    <label for="eposta">E-posta:</label>
                    <input type="text" id="eposta" name="eposta" value="@antrenor.e_posta" /><br />
                    <label for="picture">Resim:</label>
                    <input type="text" id="picture" name="picture" value="@antrenor.picture" /><br />
                    <label for="telefon">Telefon:</label>
                    <input type="text" id="telefon" name="telefon" value="@antrenor.telefon" /><br />
                    <label for="uzmanlik">Uzmanlık:</label>
                    <select id="uzmanlik" name="uzmanlik">
                        @foreach (var item in GetUzmanlikOptions(antrenor.uzmanlik))
                        {
                            <option value="@item.Value" selected="@item.Selected">@item.Text</option>
                        }
                    </select><br />
                    <input type="submit" value="Güncelle" />
                </form>
            </td>
        </tr>
    }
</table>

@functions {
    public List<SelectListItem> GetUzmanlikOptions(int selectedValue)
    {
        return new List<SelectListItem>
    {
            new SelectListItem { Text = "1 - Kilo Kazanma", Value = "1", Selected = (selectedValue == 1) },
            new SelectListItem { Text = "2 - Kilo Kaybetme", Value = "2", Selected = (selectedValue == 2) },
            new SelectListItem { Text = "3 - Kilo Koruma", Value = "3", Selected = (selectedValue == 3) },
            new SelectListItem { Text = "4 - Kas Kazanma", Value = "4", Selected = (selectedValue == 4) }
        };
    }
}

Views/AntrenorAnaPanel/Index3.cshtml
@using FitnessApp1.Models
@model MesajViewModel
<style>
    h1{
        color:rosybrown;
        margin-top:10px;
    }
    table {
        background-image: url('https://i.pinimg.com/474x/2b/a0/ac/2ba0aca799f0ce7d33cb5cf983a99baf.jpg'); /* Arkaplan resminin URL'sini buraya ekleyin */
        background-size: center; /* Resmi ekran boyutuna uyacak şekilde ölçeklendir */
        background-position: right; /* Resmi ortala */
        margin-right:200px;
        margin-left:200px;
        margin-top:40px;
    }
   body{
    background-color:wheat;
   }
    input[type="text"] {
        width: 100%;
    }
    button{
        width:100%;
    }
</style>
@{
    List<Tuple<string, string>> yeniTablo = new List<Tuple<string, string>>();

    foreach (var satir in Model.Mesajlar)
    {
        string text = satir.text;
        bool durum = satir.durum_kontrol;

        if (!durum && satir.alici_id != 0 && satir.gonderen_id != 0)
        {
            yeniTablo.Add(new Tuple<string, string>(text, ""));
        }
        if (durum && satir.alici_id != 0 && satir.gonderen_id != 0)
        {
            yeniTablo.Add(new Tuple<string, string>("", text));
        }
    }
}
<h1>SOHBETİNİZ</h1>
<table>
    @foreach (var satir in yeniTablo)
    {
        <tr>
            <td>
                @if (!string.IsNullOrEmpty(satir.Item1))
                {
                    <img src="@ViewBag.pictureKullanici" style="width: 20px; height: 20px;" />
                }
            </td>
            <td>@satir.Item1</td>

            <td>@satir.Item2</td>
            <td>
                @if (!string.IsNullOrEmpty(satir.Item2))
                {
                    <img src="@ViewBag.pictureAntrenor" style="width: 20px; height: 20px;" />
                }
            </td>

        </tr>
    }
</table>
<form method="post" asp-controller="AntrenorAnaPanel" asp-action="AntrenorMesajGonder">

    <input type="hidden" name="antrenor_id" value="@ViewBag.antrenor_id" />
    <input type="hidden" name="kullanici_id" value="@ViewBag.kullanici_id" />
    <td><input type="text" name="mesaj" placeholder="Mesajiniz" required /></td>

    <button type="submit">GÖNDER</button>
</form>