Controllers/AdminPaneliController.cs
using DataAccessLayer.Concrete;
using FitnessApp1.Models;
using FitnessApp1.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace FitnessApp1.Controllers
{
    public class AdminPaneliController : Controller
    {
        private readonly Context _context;

        public AdminPaneliController(Context context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            // Tüm kullanıcıları ve antrenörleri ayrı listelere al
            var tumKullanicilar = _context.Kullanicilar.ToList();
            var tumAntrenorler = _context.Antrenorler.ToList();

            // ViewModel'e verileri aktar
            var viewModel = new AdminPanelViewModel
            {
                Kullanicilar = tumKullanicilar,
                Antrenorler = tumAntrenorler
            };

            return View(viewModel);
        }
        public IActionResult Index1(int antrenorid)
        {

            ViewBag.Antrenorid = antrenorid;
            List<antrenor1> antrenorler = _context.Antrenorler.Where(bp => bp.antrenor_id == antrenorid).ToList();
            List<kullanici> kullanicilar = _context.Kullanicilar.Where(bp => bp.antrenor_id == antrenorid).ToList();
           
            String pictureAntrenor = "";

            foreach (var item in antrenorler)
            {
                pictureAntrenor = item.picture;
            }
            ViewBag.pictureAntrenor = pictureAntrenor;
            String pictureKullanici = "";

            foreach (var item in kullanicilar)
            {
                pictureKullanici = item.picture;
            }
            ViewBag.pictureKullanici = pictureKullanici;


            var model = new AdminPanelViewModel
            {

                Antrenorler = antrenorler,
                Kullanicilar = kullanicilar
            };



            return View(model);
        }
        public List<egzersiz_programi> TumEgzersizleriGetir()
        {
            List<egzersiz_programi> egzersizler = _context.EgzersizProgramlari.ToList();
            return egzersizler;
        }
        [HttpPost]
        public IActionResult EgzersizEkle(int kullanici_id, int antrenor_id, int hedef, int set_sayi, string video_link, DateTime baslama_tarih, string program_sure, string egzersiz_ad)
        {
            try
            {

                List<egzersiz_programi> egzersizler = TumEgzersizleriGetir();
                int idm = 0;
                foreach (var item in egzersizler)
                {
                    idm = item.id;

                }
                idm += idm;
                // Yeni veriyi oluştur
                var yeniEgzersiz = new egzersiz_programi
                {
                    id = idm,
                    kullanici_id = kullanici_id,
                    antrenor_id = antrenor_id,
                    hedef = hedef,
                    set_sayi = set_sayi,
                    video_link = video_link,
                    baslama_tarih = baslama_tarih,
                    program_sure = program_sure,
                    egzersiz_ad = egzersiz_ad
                };

                // Veritabanına yeni veriyi ekle
                _context.EgzersizProgramlari.Add(yeniEgzersiz);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                // Hata durumunda hata mesajıyla birlikte Index sayfasına geri dön
                ViewBag.UpdateError = "Bir hata oluştu. Lütfen tekrar deneyin.";
                return RedirectToAction("Index", new { id = kullanici_id });
            }
        }
        public List<kullanici> TumKullanicilariiGetir()
        {
            List<kullanici> kullanicilar = _context.Kullanicilar.ToList();
            return kullanicilar;
        }
        public List<antrenor1> TumAntrenorleriGetir()
        {
            List<antrenor1> antrenorler = _context.Antrenorler.ToList();
            return antrenorler;
        }
        [HttpPost]
        public IActionResult Delete(int kullaniciId)
        {
            var kullanici = _context.Kullanicilar.FirstOrDefault(k => k.kullanici_id == kullaniciId);
            if (kullanici != null)
            {
                _context.Kullanicilar.Remove(kullanici);
                _context.SaveChanges();
                // Silme işlemi başarılı oldu, gerekli yönlendirme yapılabilir veya bir mesaj gösterilebilir.
                return RedirectToAction("Index"); // Örneğin, kullanıcıları listeleme sayfasına geri dönebilirsin.
            }
            else
            {
                // Kullanıcı bulunamadı veya silinemediğinde bir hata mesajı gösterebilirsin.
                return NotFound(); // Örneğin, 404 sayfasına yönlendirme yapabilirsin.
            }
        }
        [HttpPost]
        public IActionResult DeleteAntrenor(int antrenorId)
        {
            var antrenor = _context.Antrenorler.FirstOrDefault(a => a.antrenor_id == antrenorId);
            if (antrenor != null)
            {
                // Kullanıcıları bul ve ilişkilendirilmiş antrenör_id'leri güncelle
                var usersToUpdate = _context.Kullanicilar.Where(k => k.antrenor_id == antrenorId).ToList();
                foreach (var user in usersToUpdate)
                {
                    user.antrenor_id = 0; // veya başka bir değer atayabilirsin, örneğin null
                }

                _context.Antrenorler.Remove(antrenor);
                _context.SaveChanges();
                // Silme işlemi başarılı oldu, gerekli yönlendirme yapılabilir veya bir mesaj gösterilebilir.
                return RedirectToAction("Index"); // Örneğin, antrenörleri listeleme sayfasına geri dönebilirsin.
            }
            else
            {
                // Antrenör bulunamadı veya silinemediğinde bir hata mesajı gösterebilirsin.
                return NotFound(); // Örneğin, 404 sayfasına yönlendirme yapabilirsin.
            }
        }
        [HttpPost]
        public IActionResult DeleteBeslenme(int id)
        {
            var beslenme = _context.BeslenmeProgramlari.FirstOrDefault(k => k.id == id);
            if (beslenme != null)
            {
                _context.BeslenmeProgramlari.Remove(beslenme);
                _context.SaveChanges();
                // Silme işlemi başarılı oldu, gerekli yönlendirme yapılabilir veya bir mesaj gösterilebilir.
                return RedirectToAction("Index"); // Örneğin, kullanıcıları listeleme sayfasına geri dönebilirsin.
            }
            else
            {
                // Kullanıcı bulunamadı veya silinemediğinde bir hata mesajı gösterebilirsin.
                return NotFound(); // Örneğin, 404 sayfasına yönlendirme yapabilirsin.
            }
        }
        [HttpPost]
        public IActionResult DeleteEgzersiz(int id)
        {
            var egzersiz = _context.EgzersizProgramlari.FirstOrDefault(k => k.id == id);
            if (egzersiz != null)
            {
                _context.EgzersizProgramlari.Remove(egzersiz);
                _context.SaveChanges();
                // Silme işlemi başarılı oldu, gerekli yönlendirme yapılabilir veya bir mesaj gösterilebilir.
                return RedirectToAction("Index"); // Örneğin, kullanıcıları listeleme sayfasına geri dönebilirsin.
            }
            else
            {
                // Kullanıcı bulunamadı veya silinemediğinde bir hata mesajı gösterebilirsin.
                return NotFound(); // Örneğin, 404 sayfasına yönlendirme yapabilirsin.
            }
        }
        [HttpPost]
        public IActionResult DeleteVersiyon(int id)
        {
            var versiyon = _context.GuncelVersiyon.FirstOrDefault(k => k.id == id);
            if (versiyon != null)
            {
                _context.GuncelVersiyon.Remove(versiyon);
                _context.SaveChanges();
                // Silme işlemi başarılı oldu, gerekli yönlendirme yapılabilir veya bir mesaj gösterilebilir.
                return RedirectToAction("Index"); // Örneğin, kullanıcıları listeleme sayfasına geri dönebilirsin.
            }
            else
            {
                // Kullanıcı bulunamadı veya silinemediğinde bir hata mesajı gösterebilirsin.
                return NotFound(); // Örneğin, 404 sayfasına yönlendirme yapabilirsin.
            }
        }


        public IActionResult Index2(int kullaniciid)
        {
            List<kullanici> tumKullanicilar = TumKullanicilariiGetir();
            int antrenor = 0;
            string picture = "";
            foreach (var item in tumKullanicilar)
            {
                if (item.kullanici_id == kullaniciid)
                {
                    picture = item.picture;
                    antrenor = item.antrenor_id;
                }
                
            }

            ViewBag.picture = picture;

            ViewBag.kullanici_id = kullaniciid;
            ViewBag.antrenor_id = antrenor;
            List<kullanici> kullanicilar = _context.Kullanicilar.Where(bp => bp.kullanici_id == kullaniciid).ToList();
            List<beslenme_programi> beslenmeprogrami = _context.BeslenmeProgramlari.Where(bp => bp.kullanici_id == kullaniciid).ToList();
            List<egzersiz_programi> egzersizprogrami = _context.EgzersizProgramlari.Where(bp => bp.kullanici_id == kullaniciid).ToList();
            List<antrenor1> antrenorler = _context.Antrenorler.Where(bp => bp.antrenor_id != antrenor).ToList();
            List<guncel_versiyon> guncelversiyonlar = _context.GuncelVersiyon.Where(bp => bp.kullanici_id == kullaniciid).ToList();
            
            var model1 = new AdminTumTablolarViewModel
            {

                Antrenorler = antrenorler,
                Kullanicilar = kullanicilar,
                BeslenmeProgramlari = beslenmeprogrami,
                EgzersizProgramlari = egzersizprogrami,

Views/AdminPaneli/Index.cshtml
@model FitnessApp1.ViewModels.AdminPanelViewModel
<style>

    topbar {
    }




    h1 {
        color: red; /* Başlık rengi */
        font-family: 'Times New Roman', Times, serif, sans-serif; /* Başlık fontu */
        margin-top: 200px;
        margin-left: 40px;
    }

    .button-background {
        margin-top: 70px;
        width: 350px;
        height: 500px;
        background-image: url('https://i.pinimg.com/474x/28/e7/ce/28e7cee8096f263938261641038f1fd1.jpg');
        background-size: cover;
        background-position: top;
        /* Yuvarlak bir arka plan oluşturmak için */
        flex-shrink: 0; /* Boyutun küçülmemesini sağla */
    }

    label {
        display: block;
        margin-bottom: 5px;
        color: red;
    }

    h2 {
        color: red; /* Başlık rengi */
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        margin-left: 25px;
        margin-top: 50px;
        font-size: 30px;
    }

    input[type="submit"] {
        width: 200px; /* Genişlik */
        height: 40px; /* Yükseklik */
        background-color: red; /* Arka plan rengi */
        color: black; /* Yazı rengi */
        border: none; /* Kenarlık olmadan */
        border-radius: 5px; /* Kenar yuvarlama */
        cursor: pointer; /* Fare üzerine gelince işaretçi tipi */
        margin-top: 10px; /* Butonlar arası boşluk */
        font-size: 16px; /* Yazı boyutu */
    }


        /* İlgili butonun üzerine gelindiğinde stilini değiştirme */
        input[type="submit"]:hover {
            background-color: red; /* Hover rengi */
        }

    button {
        color: red;
        background-color: black;
    }

    table {
        margin-left: 20px;
        border-collapse: collapse;
        width: 100%;
        background-color: white;
    }

    th, td {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        color: black;
    }

    th {
        background-color: red;
    }

    tr:nth-child(even) {
        background-color: red;
    }

    body {
        background-color: black;
    }
</style>

<h2>Tüm Kullanıcılar</h2>
<table>
    <thead>
        <tr>
            <th>Ad</th>
            <th>Soyad</th>
            <th>Düzenle</th>
            <th>Sil</th>

            <!-- Diğer sütunlar -->
        </tr>
    </thead>
    <tbody>
        @foreach (var kullanici in Model.Kullanicilar)
        {
            <tr>
                <td>@kullanici.kullanici_ad</td>
                <td>@kullanici.kullanici_soyad</td>
                <td>
                    <form method="post" asp-controller="AdminPaneli" asp-action="Index2">
                        <input type="hidden" name="kullaniciId" value="@kullanici.kullanici_id" />
                        <button type="submit">Düzenle</button>
                    </form>
                </td>
                <td>
                    <form method="post" asp-controller="AdminPaneli" asp-action="Delete">
                        <input type="hidden" name="kullaniciId" value="@kullanici.kullanici_id" />
                        <button type="submit">Sil</button>
                    </form>
                </td>

                <!-- Diğer sütunlar -->
            </tr>
        }
    </tbody>
</table>
<h2>Kullanıcı Ekle</h2>
@if (!string.IsNullOrEmpty(ViewBag.KayitError))
{
    <p style="color: red;">@ViewBag.KayitError</p>
}

<form asp-controller="AdminPaneli" asp-action="KayitKontrol" method="post">
    <div>
        <label for="kullaniciAd">Kullanıcı Adı:</label>
        <input type="text" id="kullaniciAd" name="kullaniciAd">
    </div>
    <div>
        <label for="kullaniciSoyad">Kullanıcı Soyadı:</label>
        <input type="text" id="kullaniciSoyad" name="kullaniciSoyad">
    </div>
    <div>
        <label for="dogumTarih">Doğum Tarihi:</label>
        <input type="date" id="dogumTarih" name="dogumTarih">
    </div>
    <div>
        <label>Cinsiyet:</label>
        <input type="radio" id="erkek" name="cinsiyet" value="false">
        <label for="erkek">Erkek</label>
        <input type="radio" id="kadin" name="cinsiyet" value="true">
        <label for="kadin">Kadın</label>
    </div>
    <div>
        <label for="kullaniciEposta">E-posta:</label>
        <input type="email" id="kullaniciEposta" name="kullaniciEposta">
    </div>
    <div>
        <label for="telefon">Telefon:</label>
        <input type="text" id="telefon" name="telefon">
    </div>
    <div>
        <label for="picture">Profil Resmi Yolu:</label>
        <input type="text" id="picture" name="picture">
    </div>
    <div>
        <label for="sifre">Şifre:</label>
        <input type="password" id="sifre" name="sifre">
    </div>
    <div>
        <label for="hedef">Hedef:</label>
        <select id="hedef" name="hedef">
            <option value="1">Kilo Kazanma</option>
            <option value="2">Kilo Kaybetme</option>
            <option value="3">Kilo Koruma</option>
            <option value="4">Kas Kazanma</option>
        </select>
    </div>
    <div>
        <input type="submit" value="Kayıt Ol">
    </div>
</form>

<h2>Tüm Antrenörler</h2>
<table>
    <thead>
        <tr>
            <th>Ad</th>
            <th>Soyad</th>
            <th>Düzenle</th>
            <th>Sil</th>
            <!-- Diğer sütunlar -->
        </tr>
    </thead>
    <tbody>
        @foreach (var antrenor in Model.Antrenorler)
        {
            <tr>
                <td>@antrenor.antrenor_ad</td>
                <td>@antrenor.antrenor_soyad</td>
                <td>
                    <form method="post" asp-controller="AdminPaneli" asp-action="Index1">
                        <input type="hidden" name="antrenorId" value="@antrenor.antrenor_id" />
                        <button type="submit">Düzenle</button>
                    </form>
                </td>

                <td>
                    <form method="post" asp-controller="AdminPaneli" asp-action="DeleteAntrenor">
                        <input type="hidden" name="antrenorId" value="@antrenor.antrenor_id" />
                        <button type="submit">Sil</button>
                    </form>
                </td>

                <!-- Diğer sütunlar -->
            </tr>
        }
    </tbody>
</table>
<h2>Antrenör Ekle</h2>
@if (!string.IsNullOrEmpty(ViewBag.KayitError))
{
    <p style="color: red;">@ViewBag.KayitError</p>
}

<form asp-controller="AdminPaneli" asp-action="KayitKontrol1" method="post">
    <div>
        <label for="antrenorad">Antrenor Adı:</label>
        <input type="text" id="antrenorad" name="antrenorad">
    </div>
    <div>
        <label for="antrenorsoyad">Antrenor Soyadı:</label>
        <input type="text" id="antrenorsoyad" name="antrenorsoyad">
    </div>
    <div>
        <label for="eposta">E-posta:</label>
        <input type="email" id="eposta" name="eposta">
    </div>
    <div>
        <label for="telefon">Telefon:</label>
        <input type="text" id="telefon" name="telefon">
    </div>
    <div>
        <label>Cinsiyet:</label>
        <input type="radio" id="erkek" name="cinsiyet" value="false">
        <label for="erkek">Erkek</label>
        <input type="radio" id="kadin" name="cinsiyet" value="true">
        <label for="kadin">Kadın</label>
    </div>
    <div>
        <label for="picture">Profil Resmi Yolu:</label>
        <input type="text" id="picture" name="picture">
    </div>
    <div>
        <label for="sifre">Şifre:</label>
        <input type="password" id="sifre" name="sifre">
    </div>
    <div>
        <label for="uzmanlik">Uzmanlik:</label>
        <select id="uzmanlik" name="uzmanlik">
            <option value="1">Kilo Kazanma</option>
            <option value="2">Kilo Kaybetme</option>
            <option value="3">Kilo Koruma</option>
            <option value="4">Kas Kazanma</option>
        </select>
    </div>
    <div>
        <input type="submit" value="Kayıt Ol">
    </div>
</form>

Views/AdminPaneli/Index1.cshtml
@model FitnessApp1.ViewModels.AdminPanelViewModel
<style>

    topbar {
    }




    h1 {
        color: red; /* Başlık rengi */
        font-family: 'Times New Roman', Times, serif, sans-serif; /* Başlık fontu */
        margin-top: 200px;
        margin-left: 40px;
    }

    .button-background {
        margin-top: 70px;
        width: 350px;
        height: 500px;
        background-image: url('https://i.pinimg.com/474x/28/e7/ce/28e7cee8096f263938261641038f1fd1.jpg');
        background-size: cover;
        background-position: top;
        /* Yuvarlak bir arka plan oluşturmak için */
        flex-shrink: 0; /* Boyutun küçülmemesini sağla */
    }

    label {
        display: block;
        margin-bottom: 5px;
        color: red;
    }

    h2 {
        color: red; /* Başlık rengi */
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        margin-left: 25px;
        margin-top: 50px;
        font-size: 30px;
    }

    input[type="submit"] {
        width: 200px; /* Genişlik */
        height: 40px; /* Yükseklik */
        background-color: red; /* Arka plan rengi */
        color: black; /* Yazı rengi */
        border: none; /* Kenarlık olmadan */
        border-radius: 5px; /* Kenar yuvarlama */
        cursor: pointer; /* Fare üzerine gelince işaretçi tipi */
        margin-top: 10px; /* Butonlar arası boşluk */
        font-size: 16px; /* Yazı boyutu */
    }


        /* İlgili butonun üzerine gelindiğinde stilini değiştirme */
        input[type="submit"]:hover {
            background-color: red; /* Hover rengi */
        }

    button {
        color: red;
        background-color: black;
    }

    table {
        margin-left: 20px;
        border-collapse: collapse;
        width: 100%;
        background-color: white;
    }

    th, td {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        color: black;
    }

    th {
        background-color: red;
    }

    tr:nth-child(even) {
        background-color: red;
    }

    body {
        background-color: black;
    }
</style>


<h1>Antrenör Bilgileri</h1>

@foreach (var antrenor in Model.Antrenorler)
{
    <div>
        <h3>@antrenor.antrenor_ad @antrenor.antrenor_soyad</h3>
        <h3>@antrenor.antrenor_id</h3>
        @if (ViewBag.pictureAntrenor == "")
        {
            <img src="https://i.pinimg.com/474x/fd/81/76/fd81760500afdbae097cb23b1b720c76.jpg" width="150" height="150">
        }
        @if (ViewBag.pictureAntrenor != "")
        {
            <img src="@ViewBag.pictureAntrenor" width="150" height="150">
        }

    <form asp-controller="AdminPaneli" asp-action="UpdateAntrenor" method="post">
        <input type="hidden" name="id" value="@antrenor.antrenor_id" />
        <label for="ad">Ad:</label>
        <input type="text" id="ad" name="ad" value="@antrenor.antrenor_ad" /><br />
        <label for="soyad">Soyad:</label>
        <input type="text" id="soyad" name="soyad" value="@antrenor.antrenor_soyad" /><br />


        <label for="picture">Picture:</label>
        <input type="text" id="picture" name="picture" value="@antrenor.picture" /><br />

        <label for="eposta">E-posta:</label>
        <input type="text" id="eposta" name="eposta" value="@antrenor.e_posta" /><br />
        <label for="telefon">Telefon:</label>
        <input type="text" id="telefon" name="telefon" value="@antrenor.telefon" /><br />
        <label for="uzmanlik">Uzmanlık:</label>
        <select id="uzmanlik" name="uzmanlik">
            @foreach (var item in GetUzmanlikOptions(antrenor.uzmanlik))
            {
                <option value="@item.Value" selected="@item.Selected">@item.Text</option>
            }
        </select><br />
        <input type="submit" value="Güncelle" />
    </form>
    </div>
}

<h1>Bağlı Kullanıcılar</h1>

<table>
    <thead>
        <tr>
            <th>Ad</th>
            <th>Soyad</th>
            <th>İd</th>
            <th>Cinsiyet</th>
            <th>Antrenör İd</th>
            <th>Doğum Tarih</th>
            <th>Eposta</th>
            <th>Picture</th>
            <th>Hedef</th>
            <th>Telefon</th>
            <th>Duzenle</th>


        </tr>
    </thead>
    <tbody>
        @foreach (var kullanici in Model.Kullanicilar)
        {
            <tr>
                <td>@kullanici.kullanici_ad</td>
                <td>@kullanici.kullanici_soyad</td>
                <td>@kullanici.kullanici_id</td>
                <td>@kullanici.cinsiyet</td>
                <td>@kullanici.antrenor_id</td>
                <td>@kullanici.dogum_tarih</td>
                <td>@kullanici.e_posta</td>
                <td>@kullanici.picture</td>
                <td>@kullanici.hedef</td>
                <td>@kullanici.telefon</td>
                <td>
                    <form method="post" asp-controller="AdminPaneli" asp-action="Index2">
                        <input type="hidden" name="kullaniciId" value="@kullanici.kullanici_id" />
                        <button type="submit">Düzenle</button>
                    </form>
                </td>


            </tr>
        }
    </tbody>
</table>
@functions {
    public List<SelectListItem> GetUzmanlikOptions(int selectedValue)
    {
        return new List<SelectListItem>
    {
            new SelectListItem { Text = "1 - Kilo Kazanma", Value = "1", Selected = (selectedValue == 1) },
            new SelectListItem { Text = "2 - Kilo Kaybetme", Value = "2", Selected = (selectedValue == 2) },
            new SelectListItem { Text = "3 - Kilo Koruma", Value = "3", Selected = (selectedValue == 3) },
            new SelectListItem { Text = "4 - Kas Kazanma", Value = "4", Selected = (selectedValue == 4) }
        };
    }
}